name: mobile-price-classification

services:
  ml_service:
    image: ml_service:1
    ports:
      - "8001:8000"
    volumes:
      - ./models:/models
    networks:
      - net
     
  requests:
    image: requests:0
    deploy: 
      replicas: 1
      restart_policy:
        condition: always
        delay: 5s
    networks:
      - net


  prometheus:
    image: prom/prometheus
    ports: 
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - "./prometheus/:/etc/prometheus/"
    hostname: prometheus
    networks:
      - net

  
  graphana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - "./grafana/data:/var/lib/grafana"
    networks:
      - net
      
networks:
  net:
    driver: bridge